apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.5.3
    helm:
      values: |
        features:
          admissionReports:
            enabled: false
          aggregateReports:
            enabled: false
          policyReports:
            enabled: false
          validatingAdmissionPolicyReports:
            enabled: false
        admissionController:
          replicas: 1
        backgroundController:
          replicas: 1
        cleanupController:
          enabled: false
        reportsController:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
