apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 7.0.0
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          limits_config:
            ingestion_burst_size_mb: 128
            ingestion_rate_mb: 64
          commonConfig:
            path_prefix: /tmp/loki
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: filesystem
            filesystem:
              chunks_directory: /tmp/loki/chunks
              rules_directory: /tmp/loki/rules
          rulerConfig:
            wal:
              dir: /tmp/loki/ruler-wal
          storage_config:
            bloom_shipper:
              working_directory: /tmp/loki/data/bloomshipper
        singleBinary:
          replicas: 1
          persistence:
            enabled: false
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        minio:
          enabled: false
        gateway:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
