apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    chart: secrets-store-csi-driver
    targetRevision: 1.6.0
    helm:
      values: |
        syncSecret:
          enabled: false
        enableSecretRotation: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

