{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "orders-api.name" . }}
  labels:
    {{- include "orders-api.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.secretProvider.vaultAddress | quote }}
    roleName: {{ .Values.secretProvider.roleName | quote }}
    objects: |
      - objectName: "message"
        secretPath: {{ .Values.secretProvider.secretPath | quote }}
        secretKey: {{ .Values.secretProvider.secretKey | quote }}
{{- end }}

