apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog-api.name" . }}
  labels:
    {{- include "catalog-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "catalog-api.name" . }}
  template:
    metadata:
      labels:
        {{- include "catalog-api.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "catalog-api.name" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 65533
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ include "catalog-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: {{ include "catalog-api.name" . | quote }}
            - name: APP_VERSION
              value: {{ .Chart.AppVersion | quote }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "catalog-api.name" . }}
